# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Demo' do

pod 'LTNavigationBar', '~> 2.1.2'
pod 'RAMAnimatedTabBarController'

end

target 'DemoTests' do

end

